/** MCP 专用会话与 AgentTask 管理工具。 */
import { useAppStore } from '../../../store/useAppStore';
import { pauseAgentTask, stopAgentTask } from '../agentTaskControl';
import { resumeAgentTaskExecution } from '../conversationExecutionController';
import { registerAgentTool, type AgentToolExecutionResult } from '../toolRegistry';

const mcpOnly = (context: { conversationId: string }) => context.conversationId.startsWith('mcp-control-');
const authorize = (context: { projectId: string; conversationId: string }) => ({ allowed: mcpOnly(context) && useAppStore.getState().currentProjectId === context.projectId, reason: '会话与任务管理只允许当前项目的 MCP 控制会话调用' });
const fail = (summary: string, errorCode: string): AgentToolExecutionResult => ({ status: 'error', summary, modelContent: summary, errorCode });

function publicConversation(id: string) {
  const conversation = useAppStore.getState().conversations.find((item) => item.id === id);
  return conversation && { id: conversation.id, title: conversation.title, pinned: conversation.pinned, archived: conversation.archived, mode: conversation.agentMode, active: conversation.id === useAppStore.getState().activeConversationId, messageCount: conversation.messageCount, createdAt: conversation.createdAt, updatedAt: conversation.updatedAt };
}

function publicTask(id: string, details = false) {
  const task = useAppStore.getState().agentTasks.find((item) => item.id === id);
  return task && {
    id: task.id, conversationId: task.conversationId, status: task.status, mode: task.mode,
    goal: task.goal.slice(0, 500), modelRounds: task.modelRounds, toolCallCount: task.toolCallCount,
    resumeCount: task.resumeCount ?? 0, resultSummary: task.resultSummary, errorCode: task.errorCode,
    createdAt: task.createdAt, updatedAt: task.updatedAt,
    ...(details ? { steps: task.steps.map((step) => ({ id: step.id, index: step.index, kind: step.kind, title: step.title, status: step.status, toolId: step.toolCall?.toolId, errorCode: step.errorCode })) } : {}),
  };
}

export function registerConversationAgentTools(): Array<() => void> {
  const common = { isAvailable: mcpOnly, authorize };
  return [
    registerAgentTool<Record<string, never>>({ id: 'conversation_list', title: '列出对话', description: '列出当前项目的对话元数据。', effect: 'read', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, ...common, execute: async (context) => { const conversations = useAppStore.getState().conversations.filter((item) => item.projectId === context.projectId && !item.deletedAt).map((item) => publicConversation(item.id)); return { status: 'success', summary: `找到 ${conversations.length} 个对话`, modelContent: JSON.stringify({ conversations }) }; } }),
    registerAgentTool<{ conversationId: string }>({ id: 'conversation_get', title: '读取对话状态', description: '读取一个对话的元数据和任务摘要，不返回消息正文。', effect: 'read', inputSchema: { type: 'object', required: ['conversationId'], additionalProperties: false, properties: { conversationId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, execute: async (context, input) => { const conversation = useAppStore.getState().conversations.find((item) => item.id === input.conversationId && item.projectId === context.projectId); if (!conversation) return fail('对话不存在', 'CONVERSATION_NOT_FOUND'); const tasks = useAppStore.getState().agentTasks.filter((task) => task.conversationId === conversation.id).map((task) => publicTask(task.id)); return { status: 'success', summary: `已读取对话“${conversation.title}”`, modelContent: JSON.stringify({ conversation: publicConversation(conversation.id), tasks }) }; } }),
    registerAgentTool<{ title?: string; activate?: boolean }>({ id: 'conversation_create', title: '创建对话', description: '在当前项目创建新对话，并可设为活动对话。', effect: 'config_write', inputSchema: { type: 'object', additionalProperties: false, properties: { title: { type: 'string', minLength: 1, maxLength: 120 }, activate: { type: 'boolean' } } }, ...common, execute: async (context, input) => { const id = useAppStore.getState().createConversation(context.projectId, input.title?.trim()); if (input.activate) useAppStore.getState().setActiveConversation(id); return { status: 'success', summary: '已创建对话', modelContent: JSON.stringify({ conversation: publicConversation(id) }) }; } }),
    registerAgentTool<{ conversationId: string; title?: string; pinned?: boolean; archived?: boolean }>({ id: 'conversation_update', title: '更新对话', description: '更新对话标题、置顶或归档状态。', effect: 'config_write', inputSchema: { type: 'object', required: ['conversationId'], additionalProperties: false, properties: { conversationId: { type: 'string', minLength: 1, maxLength: 180 }, title: { type: 'string', minLength: 1, maxLength: 120 }, pinned: { type: 'boolean' }, archived: { type: 'boolean' } } }, ...common, execute: async (context, input) => { const existing = useAppStore.getState().conversations.find((item) => item.id === input.conversationId && item.projectId === context.projectId); if (!existing) return fail('对话不存在', 'CONVERSATION_NOT_FOUND'); const { conversationId: _conversationId, ...changes } = input; useAppStore.getState().updateConversation(existing.id, { ...changes, title: changes.title?.trim(), titleSource: changes.title ? 'user' : existing.titleSource }); return { status: 'success', summary: `已更新对话“${changes.title ?? existing.title}”`, modelContent: JSON.stringify({ conversation: publicConversation(existing.id) }) }; } }),
    registerAgentTool<{ conversationId: string }>({ id: 'conversation_switch', title: '切换活动对话', description: '把当前项目的指定对话设为活动对话。', effect: 'config_write', inputSchema: { type: 'object', required: ['conversationId'], additionalProperties: false, properties: { conversationId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, execute: async (context, input) => { const existing = useAppStore.getState().conversations.find((item) => item.id === input.conversationId && item.projectId === context.projectId); if (!existing) return fail('对话不存在', 'CONVERSATION_NOT_FOUND'); useAppStore.getState().setActiveConversation(existing.id); await useAppStore.getState().loadConversationMessages(existing.id); return { status: 'success', summary: `已切换到对话“${existing.title}”`, modelContent: JSON.stringify({ conversation: publicConversation(existing.id) }) }; } }),
    registerAgentTool<{ conversationId: string }>({ id: 'conversation_delete', title: '删除对话', description: '软删除指定对话并停止、清理其 AgentTask。MCP 控制对话自身不可删除。', effect: 'permanent_delete', inputSchema: { type: 'object', required: ['conversationId'], additionalProperties: false, properties: { conversationId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, authorize: (context, input) => ({ allowed: mcpOnly(context) && input.conversationId !== context.conversationId && useAppStore.getState().conversations.some((item) => item.id === input.conversationId && item.projectId === context.projectId), reason: '对话不存在、不是当前项目对话，或不能删除 MCP 控制对话自身' }), execute: async (_context, input) => { const existing = useAppStore.getState().conversations.find((item) => item.id === input.conversationId); if (!existing) return fail('对话不存在', 'CONVERSATION_NOT_FOUND'); useAppStore.getState().removeConversation(existing.id); useAppStore.getState().removeConversationAgentTasks(existing.id); return { status: 'success', summary: `已删除对话“${existing.title}”`, modelContent: JSON.stringify({ deleted: true, conversationId: existing.id }) }; } }),
    registerAgentTool<Record<string, never>>({ id: 'agent_task_list', title: '列出 Agent 任务', description: '列出当前项目的 AgentTask 摘要。', effect: 'read', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, ...common, execute: async (context) => { const tasks = useAppStore.getState().agentTasks.filter((item) => item.projectId === context.projectId).map((item) => publicTask(item.id)); return { status: 'success', summary: `找到 ${tasks.length} 个 Agent 任务`, modelContent: JSON.stringify({ tasks }) }; } }),
    registerAgentTool<{ taskId: string }>({ id: 'agent_task_get', title: '读取 Agent 任务', description: '读取一个 AgentTask 和脱敏步骤状态。', effect: 'read', inputSchema: { type: 'object', required: ['taskId'], additionalProperties: false, properties: { taskId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, execute: async (context, input) => { const task = useAppStore.getState().agentTasks.find((item) => item.id === input.taskId && item.projectId === context.projectId); return task ? { status: 'success', summary: '已读取 Agent 任务', modelContent: JSON.stringify({ task: publicTask(task.id, true) }) } : fail('Agent 任务不存在', 'AGENT_TASK_NOT_FOUND'); } }),
    registerAgentTool<{ taskId: string; action: 'pause' | 'resume' | 'stop' }>({ id: 'agent_task_control', title: '控制 Agent 任务', description: '暂停、继续或停止当前项目的另一项 AgentTask。', effect: 'config_write', inputSchema: { type: 'object', required: ['taskId', 'action'], additionalProperties: false, properties: { taskId: { type: 'string', minLength: 1, maxLength: 180 }, action: { type: 'string', enum: ['pause', 'resume', 'stop'] } } }, ...common, authorize: (context, input) => ({ allowed: mcpOnly(context) && input.taskId !== context.taskId && useAppStore.getState().agentTasks.some((task) => task.id === input.taskId && task.projectId === context.projectId), reason: '任务不存在、不属于当前项目，或不能控制当前 MCP 审计任务自身' }), execute: async (_context, input) => { try { if (input.action === 'pause') pauseAgentTask(input.taskId, 'mcp_paused'); else if (input.action === 'stop') stopAgentTask(input.taskId); else { const result = resumeAgentTaskExecution(input.taskId); if (!result.ok) return fail(result.message || '任务无法继续', result.errorCode || 'AGENT_RESUME_FAILED'); } return { status: 'success', summary: `已${input.action === 'pause' ? '暂停' : input.action === 'stop' ? '停止' : '继续'} Agent 任务`, modelContent: JSON.stringify({ task: publicTask(input.taskId) }) }; } catch (error) { return fail(error instanceof Error ? error.message : '任务控制失败', 'AGENT_TASK_CONTROL_FAILED'); } } }),
    registerAgentTool<{ taskId: string }>({ id: 'agent_task_delete', title: '删除 Agent 任务', description: '永久删除一个已结束的 AgentTask。', effect: 'permanent_delete', inputSchema: { type: 'object', required: ['taskId'], additionalProperties: false, properties: { taskId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, authorize: (context, input) => { const task = useAppStore.getState().agentTasks.find((item) => item.id === input.taskId); return { allowed: mcpOnly(context) && input.taskId !== context.taskId && task?.projectId === context.projectId && ['completed', 'failed', 'stopped'].includes(task.status), reason: '只能删除当前项目中已结束的其他任务' }; }, execute: async (_context, input) => { const task = useAppStore.getState().agentTasks.find((item) => item.id === input.taskId); if (!task) return fail('Agent 任务不存在', 'AGENT_TASK_NOT_FOUND'); useAppStore.getState().removeAgentTask(task.id); return { status: 'success', summary: '已删除 Agent 任务', modelContent: JSON.stringify({ deleted: true, taskId: task.id }) }; } }),
  ];
}
