/** MCP 专用画布撤销/重做与输出历史管理。 */
import { useAppStore } from '../../../store/useAppStore';
import { registerAgentTool, type AgentToolExecutionResult } from '../toolRegistry';

const mcpOnly = (context: { conversationId: string }) => context.conversationId.startsWith('mcp-control-');
const authorize = (context: { projectId: string; conversationId: string }) => ({ allowed: mcpOnly(context) && useAppStore.getState().currentProjectId === context.projectId, reason: '历史管理只允许当前项目的 MCP 控制会话调用' });
const fail = (summary: string, errorCode: string): AgentToolExecutionResult => ({ status: 'error', summary, modelContent: summary, errorCode });

export function registerHistoryAgentTools(): Array<() => void> {
  const common = { isAvailable: mcpOnly, authorize };
  return [
    registerAgentTool<Record<string, never>>({ id: 'history_undo', title: '撤销画布操作', description: '撤销当前画布最近一次可撤销操作。', effect: 'canvas_write', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, ...common, execute: async () => (await useAppStore.getState().undo()) ? { status: 'success', summary: '已撤销画布操作', modelContent: JSON.stringify({ historyIndex: useAppStore.getState().historyIndex, revision: useAppStore.getState().getCurrentRevision() }) } : fail('当前没有可撤销操作', 'HISTORY_UNDO_UNAVAILABLE') }),
    registerAgentTool<Record<string, never>>({ id: 'history_redo', title: '重做画布操作', description: '重做当前画布最近一次已撤销操作。', effect: 'canvas_write', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, ...common, execute: async () => (await useAppStore.getState().redo()) ? { status: 'success', summary: '已重做画布操作', modelContent: JSON.stringify({ historyIndex: useAppStore.getState().historyIndex, revision: useAppStore.getState().getCurrentRevision() }) } : fail('当前没有可重做操作', 'HISTORY_REDO_UNAVAILABLE') }),
    registerAgentTool<{ search?: string; nodeType?: string }>({ id: 'history_list', title: '列出输出历史', description: '加载并列出当前项目输出历史的脱敏摘要，不返回本地路径或完整媒体 URL。', effect: 'read', inputSchema: { type: 'object', additionalProperties: false, properties: { search: { type: 'string', maxLength: 200 }, nodeType: { type: 'string', maxLength: 80 } } }, ...common, execute: async (_context, input) => { await useAppStore.getState().loadHistoryFromDb({ search: input.search, nodeType: input.nodeType as never }); const store = useAppStore.getState(); const records = store.outputHistoryRecords.map((entry) => ({ id: entry.id, nodeId: entry.nodeId, nodeLabel: entry.nodeLabel, nodeType: entry.nodeType, timestamp: entry.timestamp, prompt: entry.prompt.slice(0, 1000), outputPreview: entry.output.slice(0, 1000), model: entry.model, provider: entry.provider, status: entry.status, error: entry.error?.slice(0, 500) })); return { status: 'success', summary: `已读取 ${records.length}/${store.historyTotalCount} 条输出历史`, modelContent: JSON.stringify({ records, totalCount: store.historyTotalCount, hasMore: store.historyHasMore }) }; } }),
    registerAgentTool<{ entryId: string }>({ id: 'history_delete_entry', title: '删除输出历史', description: '永久删除当前项目的一条输出历史。', effect: 'permanent_delete', inputSchema: { type: 'object', required: ['entryId'], additionalProperties: false, properties: { entryId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, execute: async (_context, input) => { const entry = useAppStore.getState().outputHistoryRecords.find((item) => item.id === input.entryId); if (!entry) return fail('输出历史不存在或尚未加载', 'HISTORY_ENTRY_NOT_FOUND'); await useAppStore.getState().deleteHistoryEntry(entry.nodeId, entry.id); return { status: 'success', summary: '已删除输出历史', modelContent: JSON.stringify({ deleted: true, entryId: entry.id }) }; } }),
    registerAgentTool<{ nodeId: string }>({ id: 'history_clear_node', title: '清空节点输出历史', description: '永久清空指定节点的全部输出历史。', effect: 'permanent_delete', inputSchema: { type: 'object', required: ['nodeId'], additionalProperties: false, properties: { nodeId: { type: 'string', minLength: 1, maxLength: 180 } } }, ...common, execute: async (_context, input) => { await useAppStore.getState().clearNodeHistory(input.nodeId); return { status: 'success', summary: '已清空节点输出历史', modelContent: JSON.stringify({ cleared: true, nodeId: input.nodeId }) }; } }),
    registerAgentTool<Record<string, never>>({ id: 'history_clear_all', title: '清空项目输出历史', description: '永久清空当前项目全部输出历史。', effect: 'permanent_delete', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, ...common, execute: async () => { await useAppStore.getState().clearAllHistory(); return { status: 'success', summary: '已清空项目输出历史', modelContent: JSON.stringify({ cleared: true }) }; } }),
  ];
}
