/** MCP 专用自定义画风 CRUD。 */
import { useAppStore } from '../../../store/useAppStore';
import { registerAgentTool, type AgentToolExecutionResult } from '../toolRegistry';

const NODE_TYPES = ['ai-image', 'ai-panorama', 'ai-video'];
const mcpOnly = (context: { conversationId: string }) => context.conversationId.startsWith('mcp-control-');
const authorize = (context: { projectId: string; conversationId: string }) => ({ allowed: mcpOnly(context) && useAppStore.getState().currentProjectId === context.projectId, reason: '画风管理只允许当前项目的 MCP 控制会话调用' });
const fail = (summary: string): AgentToolExecutionResult => ({ status: 'error', summary, modelContent: summary, errorCode: 'STYLE_NOT_FOUND' });

export function registerStyleAgentTools(): Array<() => void> {
  const common = { isAvailable: mcpOnly, authorize };
  const fields = { nodeType: { type: 'string' as const, enum: NODE_TYPES }, name: { type: 'string' as const, minLength: 1, maxLength: 120 }, prompt: { type: 'string' as const, minLength: 1, maxLength: 12_000 } };
  return [
    registerAgentTool<Record<string, never>>({ id: 'style_list', title: '列出自定义画风', description: '列出全部自定义画风。', effect: 'read', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, ...common, execute: async () => { const styles = useAppStore.getState().customStyles.map(({ thumbnail: _thumbnail, ...style }) => style); return { status: 'success', summary: `找到 ${styles.length} 个自定义画风`, modelContent: JSON.stringify({ styles }) }; } }),
    registerAgentTool<{ styleId: string }>({ id: 'style_get', title: '读取自定义画风', description: '读取一个自定义画风，不返回缩略图 Base64。', effect: 'read', inputSchema: { type: 'object', required: ['styleId'], additionalProperties: false, properties: { styleId: { type: 'string', minLength: 1, maxLength: 160 } } }, ...common, execute: async (_context, input) => { const style = useAppStore.getState().customStyles.find((item) => item.id === input.styleId); if (!style) return fail('画风不存在'); const { thumbnail: _thumbnail, ...publicStyle } = style; return { status: 'success', summary: `已读取画风“${style.name}”`, modelContent: JSON.stringify({ style: publicStyle }) }; } }),
    registerAgentTool<{ nodeType: string; name: string; prompt: string }>({ id: 'style_create', title: '创建自定义画风', description: '创建并持久化一个自定义画风。', effect: 'config_write', inputSchema: { type: 'object', required: ['nodeType', 'name', 'prompt'], additionalProperties: false, properties: fields }, ...common, execute: async (_context, input) => { await useAppStore.getState().addCustomStyle({ nodeType: input.nodeType, name: input.name.trim(), prompt: input.prompt }); const style = useAppStore.getState().customStyles.at(-1)!; return { status: 'success', summary: `已创建画风“${style.name}”`, modelContent: JSON.stringify({ style }) }; } }),
    registerAgentTool<{ styleId: string; nodeType?: string; name?: string; prompt?: string }>({ id: 'style_update', title: '更新自定义画风', description: '更新已有自定义画风。', effect: 'config_write', inputSchema: { type: 'object', required: ['styleId'], additionalProperties: false, properties: { styleId: { type: 'string', minLength: 1, maxLength: 160 }, ...fields } }, ...common, execute: async (_context, input) => { const existing = useAppStore.getState().customStyles.find((item) => item.id === input.styleId); if (!existing) return fail('画风不存在'); const { styleId: _styleId, ...changes } = input; await useAppStore.getState().updateCustomStyle(existing.id, changes); return { status: 'success', summary: `已更新画风“${changes.name ?? existing.name}”`, modelContent: JSON.stringify({ styleId: existing.id }) }; } }),
    registerAgentTool<{ styleId: string }>({ id: 'style_delete', title: '删除自定义画风', description: '永久删除一个自定义画风。', effect: 'permanent_delete', inputSchema: { type: 'object', required: ['styleId'], additionalProperties: false, properties: { styleId: { type: 'string', minLength: 1, maxLength: 160 } } }, ...common, execute: async (_context, input) => { const existing = useAppStore.getState().customStyles.find((item) => item.id === input.styleId); if (!existing) return fail('画风不存在'); await useAppStore.getState().deleteCustomStyle(existing.id); return { status: 'success', summary: `已删除画风“${existing.name}”`, modelContent: JSON.stringify({ deleted: true, styleId: existing.id }) }; } }),
  ];
}
